product_type: mobile

assets:
  dirname: img

defaults:
  - scope:
      path: ''
      type: 1x
    values:
      layout: docs
  - scope:
      path: ''
      type: '11'
    values:
      layout: docs
  - scope:
      path: ''
      type: '12'
    values:
      layout: docs
  - scope:
      path: ''
      type: '13'
    values:
      layout: docs
  - scope:
      path: ''
      type: '14'
    values:
      layout: docs
  - scope:
      path: ''
      type: '15'
    values:
      layout: docs
  - scope:
      path: ''
      type: '20'
    values:
      layout: docs

collections:
  'all':
    output: true
    permalink: /:path:output_ext

# Build settings
#markdown: kramdown
# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

exclude:
  - "*.screenflow"

keep_files:
  - "references"

tutorial_project: 'https://cl.ly/3f263e2O0837/project.zip'

dev_build_number: 21

gh_link: https://github.com/couchbaselabs/couchbase-mobile-portal/tree/master/md-docs/

theme: couchbase-theme

plugins:
  - jekyll-redirect-from