collections:
  '20':
    output: true
    permalink: /:path:output_ext
version: '2.0'
cbl_version: '2.0 DB21'
sg_version: '1.5'
ios_dev_build: '2.0DB021'
android_dev_build: '2.0.0-DB021'
dev_build_release_date: 'December 20, 2017'
objc_dev_build_download_link: https://packages.couchbase.com/releases/couchbase-lite/ios/2.0DB21/couchbase-lite-objc_community_2.0DB21.zip
swift_dev_build_download_link: https://packages.couchbase.com/releases/couchbase-lite/ios/2.0DB21/couchbase-lite-swift_community_2.0DB21.zip
references:
  objc: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-objc/db021/'
  swift: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-swift/db021/'
  csharp: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-net/db021/'
  java: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-java/db021/'
platform_support:
  ios: iOS 9.0+
  tvos: tvOS 9.0+
  android: Android 4.1+
  macos: macOS 10.11+
  dotnet: .NET Core 1.0+ (.NET 4.6.1+), UWP, Xamarin iOS, Xamarin Android
  java: Java 7,8
